# Server endpoint
# clipcat-menu connects to server via unix domain socket if `server_endpoint` is a file path like:
# "/run/user/<user-id>/clipcat/grpc.sock".
# clipcat-menu connects to server via http if `server_endpoint` is a URL like: "http://127.0.0.1:45045".
server_endpoint = "/run/user/1000/clipcat/grpc.sock"

# The default finder to invoke when no "--finder=<finder>" option provided.
finder = "dmenu"

[log]
# Emit log message to a log file.
# Delete this line to disable emitting to a log file.
file_path = "~/.config/clipcat/clipredalog.log"
# Emit log message to systemd-journald.
emit_journald = true
# Emit log message to stdout.
emit_stdout = false
# Emit log message to stderr.
emit_stderr = false
# Log level.
level = "INFO"

# Options for "rofi".
[rofi]
# Length of line.
line_length = 100
# Length of menu.
menu_length = 10
# Prompt of menu.
menu_prompt = "Clipcat"
# Extra arguments to pass to `rofi`.
extra_arguments = ["-mesg", "Please select a clip"]

# Options for "dmenu".
[dmenu]
# Length of line.
line_length = 100
# Length of menu.
menu_length = 10
# Prompt of menu.
menu_prompt = "Your Clipboard SIIIRE!!"
# Extra arguments to pass to `dmenu`.
extra_arguments = [
  "-fn",
  "JetBrainsMono Nerd Font Mono,JetBrainsMono NFM Light:style=Bold,Regular:size=18",
  "-nb",
  "#333333",
  "-nf",
  "#f5f5f5",
  "-sb",
  "#333333",
  "-sf",
  "#ffd700",
]

# Customize your finder.
[custom_finder]
# External program name.
program = "fzf"
# Arguments for calling external program.
args = []
